version: '3.8'

services:
  backend:
    build: 
      context: ./cm.backend
      dockerfile: Dockerfile
    container_name: cm-backend
    ports:
      - "8000:8000"
    volumes:
      - ./cm.backend:/app
      - ./cm.backend:/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    networks:
      - cm-network
    restart: unless-stopped
    depends_on:
      - redis

  frontend:
    build:
      context: ./cm.frontend
      dockerfile: Dockerfile
    container_name: cm-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./cm.frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://cm-backend:8000
    depends_on:
      - backend
    networks:
      - cm-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  cm-network:
    driver: bridge

volumes:
  redis_data: